import { makeStyles } from '@mui/styles';
import Head from 'next/head'

const useStyles = makeStyles((theme) => ({
  container: {
    background: theme.palette.background
  }
}))
export default function Home() {
  const classes = useStyles();
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Dariush
    </div>
  )
}
